<?php
defined("MENU_YOU") or define("MENU_YOU", TRUE); 
//YOU
defined("YOU_MENU") or define("YOU_MENU", TRUE); //the hole you menu.
	defined("YOUR_DESKTOP") or define("YOUR_DESKTOP", TRUE);
	defined("YOUR_CERTS") or define("YOUR_CERTS", FALSE);
	defined("YOUR_PORTFOLIO") or define("YOUR_PORTFOLIO", FALSE);
	defined("YOUR_NEWS") or define("YOUR_NEWS", TRUE);
		defined("YOUR_SUBSCRIPTION") or define("YOUR_SUBSCRIPTION", TRUE);
	defined("YOUR_MAILBOX") or define("YOUR_MAILBOX", TRUE);
		defined("WRITE_MESSAGES") or define("WRITE_MESSAGES", TRUE);
		defined("MAILBOX_KONFIGURATION") or define("MAILBOX_KONFIGURATION", TRUE);
		defined("DELETE_MAILS") or define("DELETE_MAILS", TRUE);
	defined("MAILBOX_SHOW_UNREAD_ON_STARTPAGE") or define("MAILBOX_SHOW_UNREAD_ON_STARTPAGE", FALSE);
	defined("YOUR_CALENDER") or define("YOUR_CALENDER", TRUE);
		defined("ADD_MEETINGS") or define("ADD_MEETINGS", TRUE);
	defined("YOUR_DOCUMENTS") or define("YOUR_DOCUMENTS", TRUE);
		defined("CREATE_FOLDER") or define("CREATE_FOLDER", TRUE);
		defined("UPLOAD_DOCUMENT") or define("UPLOAD_DOCUMENT", TRUE);
		defined("ADD_WEBLINK") or define("ADD_WEBLINK", TRUE);
		defined("CLIPBOARD") or define("CLIPBOARD", TRUE);
	defined("YOUR_PROFILE") or define("YOUR_PROFILE", TRUE);
		defined("CHANGE_PROFILE_DATA") or define("CHANGE_PROFILE_DATA", TRUE);
		defined("CHANGE_PROFILE_PICTURE") or define("CHANGE_PROFILE_PICTURE", TRUE);
		defined("CHANGE_PROFILE_PRIVACY") or define("CHANGE_PROFILE_PRIVACY", TRUE);
	defined("YOUR_BOOKMARKS") or define("YOUR_BOOKMARKS", TRUE);
	defined("YOUR_SCHOOLBOOKMARKS") or define("YOUR_SCHOOLBOOKMARKS", FALSE);
	defined("YOUR_MOKODESK") or define("YOUR_MOKODESK", FALSE);
	defined("MOKODESK_URL") or define("MOKODESK_URL", "http://www.bid-owl.de/lars/");
	defined("SCHOOLS_MENU") or define("SCHOOLS_MENU", TRUE);
	defined("REST_MENU") or define("REST_MENU", TRUE);
	
		
//COURSES
defined("COURSES_MENU") or define("COURSES_MENU", TRUE);
	defined("YOUR_COURSES") or define("YOUR_COURSES", TRUE);
		defined("ADD_COURSE") or define("ADD_COURSE", TRUE);
		defined("IMPORT_COURSE_FROM_PAUL") or define("IMPORT_COURSE_FROM_PAUL", TRUE);
		defined("MANAGE_SEMESTER") or define("MANAGE_SEMESTER", TRUE);
		defined("ADD_SEMESTER") or define("ADD_SEMESTER", TRUE);
		defined("COURSE_PARTICIPANTS") or define("COURSE_PARTICIPANTS", TRUE);
		defined("COURSE_UNITS") or define("COURSE_UNITS", TRUE);
		defined("COURSE_COMMUNICATION") or define("COURSE_COMMUNICATION", TRUE);
		defined("COURSE_EXAM") or define("COURSE_EXAM", FALSE);
		defined("COURSE_LEAVE") or define("COURSE_LEAVE", TRUE);
		defined("COURSE_SHOW_MAXSIZE") or define("COURSE_SHOW_MAXSIZE", TRUE);
		defined("COURSE_SHOW_ONLY_EXTERN_MAIL") or define("COURSE_SHOW_ONLY_EXTERN_MAIL", FALSE);
	defined("ALL_COURSES") or define("ALL_COURSES", TRUE);
	defined("ADMIN_ONLY_ALL_COURSES") or define("ADMIN_ONLY_ALL_COURSES", FALSE);
	defined("COURSE_STAFF_ADD_MEMBER") or define("COURSE_STAFF_ADD_MEMBER", TRUE);
	defined("COURSE_STAFF_EXCEL_LIST") or define("COURSE_STAFF_EXCEL_LIST", TRUE);
	defined("COURSE_STAFF_CIRCULAR") or define("COURSE_STAFF_CIRCULAR", TRUE);
	defined("COURSE_STAFFLIST_MANAGE") or define("COURSE_STAFFLIST_MANAGE", TRUE);
	defined("COURSE_STAFFLIST_HIDE") or define("COURSE_STAFFLIST_HIDE", TRUE);
	defined("COURSE_STAFF") or define("COURSE_STAFF", FALSE);
	defined("COURSE_PARTICIPANTS_ADD_MEMBER") or define("COURSE_PARTICIPANTS_ADD_MEMBER", TRUE);
	defined("COURSE_PARTICIPANTS_EXCEL_LIST") or define("COURSE_PARTICIPANTS_EXCEL_LIST", TRUE);
	defined("COURSE_PARTICIPANTS_CIRCULAR") or define("COURSE_PARTICIPANTS_CIRCULAR", TRUE);
	defined("COURSE_PARTICIPANTSLIST_MANAGE") or define("COURSE_PARTICIPANTSLIST_MANAGE", TRUE);
	defined("COURSE_PREFERENCES") or define("COURSE_PREFERENCES", TRUE);
	defined("COURSE_START_ADMIN_PROFILE_ANKER") or define("COURSE_START_ADMIN_PROFILE_ANKER", TRUE);
	defined("COURSE_START_SEND_MESSAGE") or define("COURSE_START_SEND_MESSAGE", FALSE);
	defined("COURSE_SEM_APP_ENABLED") or define("COURSE_SEM_APP_ENABLED", TRUE);
	defined("COURSE_KOALAADMIN_ONLY") or define("COURSE_KOALAADMIN_ONLY", FALSE);
	defined("COURSE_PARTICIPANTS_STAFF_ONLY") or define("COURSE_PARTICIPANTS_STAFF_ONLY", FALSE);
	defined("COURSE_STAFF_FACULTY_AND_FOCUS") or define("COURSE_STAFF_FACULTY_AND_FOCUS", TRUE);
	defined("COURSE_STAFF_EXTENSIONS") or define("COURSE_STAFF_EXTENSIONS", FALSE);
	defined("COURSE_PARTICIPANTS_FACULTY_AND_FOCUS") or define("COURSE_PARTICIPANTS_FACULTY_AND_FOCUS", TRUE);
	defined("COURSE_PARTICIPANTS_COMMUNICATION") or define("COURSE_PARTICIPANTS_COMMUNICATION", TRUE);
	defined("COURSE_PARTICIPANTS_ATTENDANCE_LIST") or define("COURSE_PARTICIPANTS_ATTENDANCE_LIST", TRUE);
	defined("COURSE_PARTICIPANTS_MANAGE_MEMBERSHIP_REQUESTS") or define("COURSE_PARTICIPANTS_MANAGE_MEMBERSHIP_REQUESTS", TRUE);
	defined("COURSE_PARTICIPANTS_EXTENSIONS") or define("COURSE_PARTICIPANTS_EXTENSIONS", FALSE);
	defined("SHOW_SEMESTER_IN_HEADLINE") or define("SHOW_SEMESTER_IN_HEADLINE", TRUE);
	defined("USER_LIST_NO_PAGEING") or define("USER_LIST_NO_PAGEING", FALSE);
		//the buttons here are redundant with the buttons above
//CONTACTS
defined("CONTACTS_MENU") or define("CONTACTS_MENU", TRUE);
	defined("YOUR_CONTACTS") or define("YOUR_CONTACTS", TRUE);
	defined("PROFILE_VISITORS") or define("PROFILE_VISITORS", FALSE);
	defined("USER_SEARCH") or define("USER_SEARCH", FALSE);
//GROUPS
defined("GROUPS_MENU") or define("GROUPS_MENU", TRUE);
	defined("YOUR_GROUPS") or define("YOUR_GROUPS", TRUE);
		defined("SHOW_ALL_PUBLIC_GROUPS") or define("SHOW_ALL_PUBLIC_GROUPS", TRUE);
		defined("CREATE_GROUPS") or define("CREATE_GROUPS", TRUE);
	defined("BROWSE_GROUPS") or define("BROWSE_GROUPS", TRUE);
		defined("MANAGE_GROUPS_MEMBERSHIP") or define("MANAGE_GROUPS_MEMBERSHIP", TRUE);	
	defined("CREATE_GROUP") or define("CREATE_GROUP", TRUE);
		defined("CREATE_PUBLIC_GROUP") or define("CREATE_PUBLIC_GROUP", TRUE);
		defined("CREATE_PRIVATE_GROUP") or define("CREATE_PRIVATE_GROUP", TRUE);
		
//PROFILE
defined("PROFILE_EDIT") or define("PROFILE_EDIT", TRUE);
defined("PROFILE_PRIVACY") or define("PROFILE_PRIVACY", TRUE);
defined("PROFILE_PICTURE") or define("PROFILE_PICTURE", TRUE);
defined("PROFILE_STATUS") or define("PROFILE_STATUS", TRUE);
defined("PROFILE_EMAIL") or define("PROFILE_EMAIL", FALSE);
defined("PROFILE_GENDER") or define("PROFILE_GENDER", TRUE);
defined("PROFILE_GENERAL") or define("PROFILE_GENERAL", TRUE);
defined("PROFILE_LANGUAGE") or define("PROFILE_LANGUAGE", TRUE);
defined("PROFIL_CONTACT") or define("PROFIL_CONTACT", TRUE);
defined("PROFILE_MANAGE_CONTACT") or define("PROFILE_MANAGE_CONTACT", TRUE);
defined("PROFILE_INTRODUCE_PERSON") or define("PROFILE_INTRODUCE_PERSON", TRUE);
defined("PROFILE_SEND_MAIL") or define("PROFILE_SEND_MAIL", TRUE);	
	
defined("SERVERMENU") or define("SERVERMENU", TRUE);
defined("SERVERMONITOR") or define("SERVERMONITOR", FALSE);
defined("KOALAADMINTOOLS") or define("KOALAADMINTOOLS", TRUE);
defined("USERMANAGEMENT") or define("USERMANAGEMENT", FALSE);
	defined("USERMANAGEMENT_CUSTOMERS") or define("USERMANAGEMENT_CUSTOMERS", FALSE);
	defined("USERMANAGEMENT_CONFIGURATION") or define("USERMANAGEMENT_CONFIGURATION", FALSE);
	defined("USERMANAGEMENT_SYSTEMADMIN") or define("USERMANAGEMENT_SYSTEMADMIN", FALSE);
defined("DISCLAIMER") or define("DISCLAIMER", FALSE);
defined("CHANGE_PASSWORD") or define("CHANGE_PASSWORD", FALSE);		
?>