<?php
defined("STARTPAGE_AS_PORTAL") or define("STARTPAGE_AS_PORTAL", false);
defined("STARTPAGE_AS_PORTAL_ID") or define("STARTPAGE_AS_PORTAL_ID", 1234);
defined("STARTPAGE_REDIRECT") or define("STARTPAGE_REDIRECT", FALSE);
defined("STARTPAGE_REDIRECT_URL") or define("STARTPAGE_REDIRECT_URL", "");
?>